version: "2.2"
services:
  db:
    image: postgres:15
    container_name: db_int20
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env

  app:
    build: 
      context: .
    env_file:
      - .env
    container_name: fastapi_int20
    command: ["/int20-evo/docker/app.sh"]
    ports:
      - ${APP_PORT}:8000
    depends_on:
      - db

  # client:
  #   image: nginx
  #   container_name: frontend_hack
  #   ports:
  #       - 8080:80
  #       - 443:443
  #   volumes:
  #       - ./front:/usr/share/nginx/html
  #       - ./cert:/etc/nginx/certs
  #       - ./nginx/nginx.conf:/etc/nginx/nginx.conf